# Email configuration for critical alerts
# Replace with your actual email credentials
EMAIL_USER = "jamalahmedkashmiri@gmail.com"
EMAIL_PASSWORD = "qyjg gudu fqel rylu"

# Note: For Gmail, use App Password instead of regular password
# 1. Enable 2-factor authentication
# 2. Generate App Password in Google Account settings
# 3. Use the App Password here