# Email configuration for critical alerts
# Replace with your actual email credentials
EMAIL_USER = "jamalahmedkashmiri@gmail.com"
EMAIL_PASSWORD = "qyjg gudu fqel rylu"

# Note: For Gmail, use App Password instead of regular password
# 1. Enable 2-factor authentication
# 2. Generate App Password in Google Account settings
# 3. Use the App Password here

# Database configuration (Neon.tech free PostgreSQL)
# Sign up at https://neon.tech for free 10GB database
DB_HOST = "ep-raspy-unit-a9b1l5l9-pooler.gwc.azure.neon.tech"
DB_NAME = "neondb"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_UfcYJMEy9W7o"
DB_PORT = "5432"